### 
GET  http://localhost:4004/odata/v4/task/Tasks HTTP/1.1

### 
GET  http://localhost:4004/odata/v4/task/Tasks(36dded45-cfc8-46c1-8221-f4dd2258b656) HTTP/1.1

### 
POST  http://localhost:4004/odata/v4/task/Tasks HTTP/1.1
content-type: application/json

{
    "fileName": "defaultTrace.trc",
    "logType": "defaultTrace",
    "fileId" : ""
}


### 
GET  http://localhost:4004/odata/v4/admin/getCdsEnvKeys() HTTP/1.1

### 
GET  http://localhost:4004/odata/v4/admin/getProcessEnv() HTTP/1.1

### 
GET  http://localhost:4004/odata/v4/admin/getCfAppInstanceIndex() HTTP/1.1

### 
GET  http://localhost:4004/odata/v4/task/Timers HTTP/1.1

### 
GET  http://localhost:4004/odata/v4/task/getStatus() HTTP/1.1

### 
POST http://localhost:4004/odata/v4/task/pushToTaskQueue HTTP/1.1
content-type: application/json

{
    "parseCallback": "sample",
    "fileName": "defaultTrace.trc",
    "logType": "defaultTrace",
    "logFileChunks" : [
        "abc",
        "def"
    ],
    "fileId" : ""
}

### 
POST http://localhost:4004/odata/v4/task/Timers('0')/sap.logm.srv.TaskService.getStatus HTTP/1.1
content-type: application/json

{

}

### 
POST http://localhost:4004/odata/v4/task/readStatus HTTP/1.1
content-type: application/json

{
    "fileId" : ""
}

### 
POST http://localhost:4004/odata/v4/task/retrieveLogModelData HTTP/1.1
content-type: application/json

{
    "fileId" : "",
    "ifDeleteAfterRetrieve" : false
}

### 
POST http://localhost:4004/odata/v4/task/deleteConsumedLogModelData HTTP/1.1
content-type: application/json

{
    "fileId" : ""
}

### 
POST http://localhost:4004/odata/v4/dev/parseChunkSim HTTP/1.1
content-type: application/json

{
    "chunk": "",
    "fileName": "defaultTrace.trc",
    "logType": "defaultTrace"
}
